pipeline {
    agent any
    environment{
        VERSION - "0.1.0"
        VERSION_RC = "rc.2"
    }

    stages{
        stage('Audit tools'){
            steps
            {
                
            }
        }
        stage('Build')
        {
            steps{
                echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"

            }
        }
        
    }
}