//this is how to reference a library

/*
library identifier: 'jenkins-pipeline-demo-library@master',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'link'])
*/

pipeline {
    agent any
    environment{
        VERSION = "0.1.0"
        VERSION_RC = "rc.2"
    }
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'This is a release candidate?')
    }

    stages{
        stage('Audit tools'){
            steps
            {
             echo "chalo ye bhi kar lete hain"   
            }
        }
        stage('Build')
        {
            steps{
                echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"

            }
        }
        stage('Publish')
        {
            when{
                expression {return params.RC}
            }
            steps{
                echo "ye chala kya?"
            }
        }

    }
}

void auditTools()
{
    sh '''
    echo "is this running?"
    '''
}